#!/usr/bin/env bash
# Quick start guide for Subsidence Visualization

echo "=========================================="
echo "Subsidence Calculator - Quick Start Guide"
echo "=========================================="
echo ""
echo "Choose your visualization method:"
echo ""
echo "1. JUPYTER NOTEBOOK (Interactive, inline)"
echo "   Command: jupyter notebook subsidence_interactive.ipynb"
echo "   Features: Real-time parameter adjustment, instant plots"
echo ""
echo "2. FLASK WEB SERVER (Full-featured web interface)"
echo "   Command: python web_app.py"
echo "   Then open: http://localhost:5000"
echo "   Features: Professional UI, responsive design, shareable"
echo ""
echo "3. TERMINAL UI (Simple text interface)"
echo "   Command: python main.py"
echo "   Features: Console-based input, generates HTML map"
echo ""
echo "=========================================="
echo ""
echo "Quick start with Flask:"
echo "  cd /workspaces/Subsidence"
echo "  python web_app.py"
echo "  # Then open http://localhost:5000 in your browser"
echo ""
echo "Quick start with Jupyter:"
echo "  cd /workspaces/Subsidence"
echo "  jupyter notebook subsidence_interactive.ipynb"
echo ""
echo "=========================================="
